services:
  virtual-circuit-breaker:
    build: ./virtual-circuit-breaker
    environment:
    - TZ=Europe/Madrid
    - INTERFACE=eth0
    - APPID=0x4100
    - NS=120000
    privileged: true
    container_name: XBCR-3
    image: virtualizaciondenodoslogicos-docker-dev-local.artifact.tecnalia.dev:443/ied3-substation_virtual_nodes-virtual-circuit-breaker:latest
    networks:
    - WIFI6_Network
networks:
  WIFI6_Network:
    driver: bridge
