version: '3.8'
 
services:
  virtual-ied:
    build: ./virtual-ied
    container_name: virtual-ied
    environment:
      - TZ=Europe/Madrid
      - INTERFACE=eth0
      - APPID=0x4100
      - NS=120000
    logging:
      driver: journald
    networks:
      - sv_network
    privileged: true

  smvgentime:
    build: ./smvgentime
    container_name: smvgentime
    environment:
      - TZ=Europe/Madrid
      - INTERFACE=eth0
      - APPID=0x4100
      - NS=120000
    logging:
      driver: journald
    networks:
      - sv_network
    privileged: true

networks:
  sv_network:
    name: sv_network
    driver: bridge
  virtual_process_bus:
    name: virtual_process_bus
    driver: macvlan

