version: '3.8'
 
services:
  virtual-circuit-breaker:
    build: ./virtual-circuit-breaker
    container_name: virtual-circuit-breaker
    environment:
      - TZ=Europe/Madrid
      - INTERFACE=eno1
      - APPID=0x4100
      - NS=120000
    networks:
      - sv_network
    privileged: true

  virtual-104-gtw:
    build: ./virtual-104-gtw
    container_name: virtual-104-gtw
    environment:
      - TZ=Europe/Madrid
      - INTERFACE=eno1
      - APPID=0x4100
      - NS=120000
    network_mode: host
    privileged: true
  
  virtual-ied:
    build: ./virtual-ied
    container_name: virtual-ied
    environment:
      - TZ=Europe/Madrid
      - INTERFACE=eth0
      - APPID=0x4100
      - NS=120000
    logging:
      driver: journald
    networks:
      - sv_network
    privileged: true

  virtual-merging-unit:
    build: ./virtual-merging-unit
    container_name: virtual-merging-unit
    environment:
      - TZ=Europe/Madrid
      - INTERFACE=eth0
      - APPID=0x4100
      - NS=120000
    networks:
      - sv_network
    privileged: true

  smvgentime:
    build: ./smvgentime
    container_name: smvgentime
    environment:
      - TZ=Europe/Madrid
      - INTERFACE=eth0
      - APPID=0x4100
      - NS=120000
    logging:
      driver: journald
    networks:
      - sv_network
    privileged: true

  virtual-ied-configs:
    build: 
      context: .
      dockerfile: virtual-ied-configs/Dockerfile
    container_name: virtual-ied-configs
    network_mode: bridge
    privileged: true

  virtual_goose:
    build: ./virtual_goose
    container_name: virtual_goose
    environment:
      - TZ=Europe/Madrid
      - INTERFACE=eno1
      - APPID=0x4100
      - NS=120000
    networks:
      - sv_network
    privileged: true

networks:
  sv_network:
    name: sv_network
    driver: bridge
  virtual_process_bus:
    name: virtual_process_bus
    driver: macvlan
