services:
  virtual-merging-unit:
    build: ./virtual-merging-unit
    environment:
    - TZ=Europe/Madrid
    - INTERFACE=eth0
    - APPID=0x4100
    - NS=120000
    privileged: true

  smvgentime:
    build: ./smvgentime
    environment:
    - TZ=Europe/Madrid
    - INTERFACE=eth0
    - APPID=0x4100
    - NS=120000
    logging:
      driver: journald
    privileged: true


  virtual-circuit-breaker:
    build: ./virtual-circuit-breaker
    environment:
    - TZ=Europe/Madrid
    - INTERFACE=eth0
    - APPID=0x4100
    - NS=120000
    privileged: true

  virtual-ied:
    build: ./virtual-ied
    environment:
    - TZ=Europe/Madrid
    - INTERFACE=eth0
    - APPID=0x4100
    - NS=120000
    logging:
      driver: journald
    privileged: true

  virtual-104-gtw:
    build: ./virtual-104-gtw
    environment:
    - TZ=Europe/Madrid
    - INTERFACE=eth0
    - APPID=0x4100
    - NS=120000
    privileged: true
