version: '3.8'
 
services:
  virtual-circuit-breaker:
    build: ./virtual-circuit-breaker
    container_name: virtual-circuit-breaker
    environment:
      - TZ=Europe/Madrid
      - INTERFACE=eno1
      - APPID=0x4100
      - NS=120000
    network_mode: host
    privileged: true

  # virtual-104-gtw:
  #   build: ./virtual-104-gtw
  #   container_name: virtual-104-gtw
  #   environment:
  #     - TZ=Europe/Madrid
  #     - INTERFACE=eno1
  #     - APPID=0x4100
  #     - NS=120000
  #   network_mode: host
  #   privileged: true
  
  virtual-ied:
    build: ./virtual-ied
    container_name: virtual-ied
    environment:
      - TZ=Europe/Madrid
      - INTERFACE=eno1
      - APPID=0x4100
      - NS=120000
    network_mode: host
    privileged: true

  virtual-merging-unit:
    build: ./virtual-merging-unit
    container_name: virtual-merging-unit
    environment:
      - TZ=Europe/Madrid
      - INTERFACE=eno1
      - APPID=0x4100
      - NS=120000
    network_mode: host
    privileged: true


  # virtual-ied-configs:
  #   build: ./virtual-ied-configs
  #   container_name: virtual-ied-configs
  #   volumes:
  #     - ./virtual-ied-configs/app/ied_config.json:/app/ied_config.json
  #   network_mode: bridge
  #   privileged: true